[package]
name = "ammonia"
version = "1.0.0-rc1" # remember to update html_root_url
authors = ["Michael Howell <michael@notriddle.com>"]
description = "HTML Sanitization"
keywords = [ "sanitization", "html", "security", "xss" ]
license = "MIT / Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/ammonia/"
repository = "https://github.com/notriddle/ammonia"
categories = [ "web-programming", "text-processing" ]

[dependencies]
html5ever = "0.20"
maplit = "0.1"
tendril = "0.4"
url = "1.5"
lazy_static = "0.2"
